name: anrokku
version: git
summary: Anrokku
description: |
  Anrokku is a puzzle game

grade: devel
confinement: devmode

apps:
  anrokku:
    command: bin/main.py

parts:
  #setup:
  #  plugin: python
  #  python-version: python3
  #  python-packages: [pycairo,pygobject]
  anrokku:
    #after: [setup]
    plugin: python
    python-version: python2
    source: .
    stage-packages: [python3-gi-cairo,python3-gi,libc6,gir1.2-gtk-3.0,libgtk-3-dev]
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp main.py $SNAPCRAFT_PART_INSTALL/bin/
      cp coche.py $SNAPCRAFT_PART_INSTALL/bin/
      cp -r data $SNAPCRAFT_PART_INSTALL/bin/

    